project:
  type: website
  output-dir: _site
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600
  resources:
    - _pdf/**
  render:
    - index.qmd
    - posts/**/index.qmd

website:
  title: "Grafici che fanno pensare"
  site-url: https://paolovolterra.github.io/blog
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true
  twitter-card:
    creator: "@ghibbli"
  repo-actions: [edit, issue]
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Post
    right:
      - icon: github
        href: https://github.com/paolovolterra/blog

  page-footer:
    center:
      - text: "© 2025 Paolo Volterra"
      - text: "Feed RSS"
        href: posts/index.xml

format:
  html:
    css: MCC.css
    toc: true
    code-copy: true
    theme:
      - pulse
      - BeatrizMilz.scss
  pdf:
    output-dir: _pdf   # i PDF vanno in _pdf/
    
execute:
  default-language: python
  echo: true
  warning: false
  error: false
  cache: true
  freeze: auto
